version: "3"

services:
  app:
    image: token_auth:1.3
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./TokenBasedAuth:/TokenBasedAuth
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=TokenBasedAuth
      - DB_USER=postgres
      - DB_PASS=admin123
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=TokenBasedAuth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    ports:
    - "5432:5432"
volumes:
  postgres_data: